name: Daily Automated Commit

on:
  schedule:
    # Runs daily at 12:00 PM UTC
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Git config with email 21f1001577@ds.study.iitm.ac.in
      run: |
        git config user.name "GitHub Actions"
        git config user.email "21f1001577@ds.study.iitm.ac.in"
        
    - name: Create empty commit for daily tracking
      run: |
        git commit --allow-empty -m "Daily automated commit - $(date)"
        git push
